### ISSUE TITLE
express.loggerを使おうとすると、サーバー起動でエラーが表示される

### ISSUE THREAD

**Issue by kamimi01** [kamimi01/BasicofExpressjs1#2]
問題：express.loggerを使おうとすると、下記のエラーが表示される
```
Error: Most middleware (like logger) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (/Users/mikaurakawa/Desktop/Node_Projects/BasicofExpressjs1/myapp/node_modules/express/lib/express.js:112:13)
    at Object.<anonymous> (/Users/mikaurakawa/Desktop/Node_Projects/BasicofExpressjs1/myapp/app.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by kamimi01** [comment]
原因・対処方法：ドットインストールの補足情報の通り実行する
参考：https://dotinstall.com/lessons/basic_expressjs/26507
